In [2]:
#載入套件
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
#匯入資料（但所有變數名稱皆是隱藏，但需要預測最後TARGET CLASS是哪個）
#index_col=0代表設定第一行為index

df = pd.read_excel('top200_training.xlsx')
df_copy = df.copy()
df.head()

證券代碼           簡稱      年月  市值(百萬元)  收盤價(元)_年     本益比    股價淨值比    股價營收比  \
0  19972330   台積電         199712   457105     15.24  3.4636  0.89594  1.41640   
1      2303  聯電           199712   263536     20.55  9.1333  1.27240  3.38550   
2      2002  中鋼           199712   181781      5.53  2.6209  0.35770  0.42117   
3      1303  南亞           199712   175637     14.81  6.6116  0.74949  0.40821   
4      2357  華碩           199712   166991    158.47  7.0746  2.59620  2.39490   

   M淨值報酬率─稅後  資產報酬率ROA  ...   利潤邊際NPM   負債/淨值比   M流動比率   M速動比率  M存貨週轉率 (次)  \
0   0.144140  0.223790  ...  0.408870  0.55256  223.86  177.18        5.99   
1   0.111460  0.145880  ...  0.388200  0.30889  338.15  303.48        5.27   
2   0.077890  0.136380  ...  0.160150  0.75094   85.46   26.60        4.10   
3   0.035977  0.099458  ...  0.061046  1.76440  133.30   80.55        4.36   
4   0.300880  0.356970  ...  0.329330  0.18643  556.46  476.72        7.60   

   M應收帳款週轉次  M營業利益成長率  M稅後淨利成長率   Return  ReturnMean_year_Label  
0      6.34    -18.13     -8.00  -6.3648                      1  
1      6.80    -41.39     27.37 -18.0049                      1  
2     22.41     44.39     63.01  -9.2224                      1  
3      7.00      8.65    -15.94 -12.0864                      1  
4     23.93     52.07     84.82  46.2737                      1  

[5 rows x 21 columns]

In [4]:
#由於KNN分類法是藉由確認最近的觀察值來預測分類，因此變數的比例就會影響很大
#載入標準化比例尺(StandardScaler)套件
from sklearn.preprocessing import StandardScaler
columns_to_exclude = ['簡稱', '證券代碼', '年月','ReturnMean_year_Label']

# 排除指定的欄位
features_to_scale = df.drop(columns=columns_to_exclude)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features_to_scale)

# 將標準化後的特徵資料轉換為 DataFrame
df_feat = pd.DataFrame(scaled_features, columns=features_to_scale.columns)
df_feat.head()

市值(百萬元)  收盤價(元)_年       本益比     股價淨值比     股價營收比  M淨值報酬率─稅後  資產報酬率ROA  \
0  3.256366 -0.391126 -0.019625 -0.340375 -0.072598   0.834428  0.304162   
1  1.711336 -0.300845 -0.019622 -0.195366  0.296257   0.491610  0.115308   
2  1.058783 -0.556217 -0.019625 -0.547700 -0.259026   0.139455  0.092280   
3  1.009743 -0.398437 -0.019623 -0.396786 -0.261453  -0.300218  0.002781   
4  0.940732  2.044084 -0.019623  0.314549  0.110696   2.478654  0.626991   

   營業利益率OPM   利潤邊際NPM    負債/淨值比     M流動比率     M速動比率  M存貨週轉率 (次)  M應收帳款週轉次  \
0  1.681140  0.995826 -0.497834  0.069322  0.212942   -0.040430 -0.188611   
1  0.355917  0.933705 -0.814563  0.584604  1.079085   -0.041177 -0.172133   
2  0.927802  0.248334 -0.239975 -0.554662 -0.819710   -0.042391  0.387039   
3  0.008775 -0.049509  1.077348 -0.338973 -0.449730   -0.042122 -0.164969   
4  1.207586  0.756780 -0.973740  1.568867  2.267135   -0.038760  0.441488   

   M營業利益成長率  M稅後淨利成長率    Return  
0 -0.043700 -0.038994 -0.084482  
1 -0.049608 -0.011682 -0.254944  
2 -0.027819  0.015838 -0.126330  
3 -0.036898 -0.045125 -0.168271  
4 -0.025868  0.032680  0.686376

In [ ]:
#選擇特定欄位分析
#from sklearn.preprocessing import StandardScaler

# 指定要選擇的欄位
#selected_columns = ['特定欄位1', '特定欄位2', '特定欄位3']

# 選擇指定的欄位
#features_to_scale = df[selected_columns]

#scaler = StandardScaler()
#scaled_features = scaler.fit_transform(features_to_scale)

# 將標準化後的特徵資料轉換為 DataFrame
#df_feat = pd.DataFrame(scaled_features, columns=selected_columns)
#df_feat.head()

In [30]:
#將資料分成訓練組及測試組(自動分割(以index做連結))
from sklearn.model_selection import train_test_split

X = df_feat
y = df['ReturnMean_year_Label']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [31]:
#使用KNN演算法
from sklearn.neighbors import KNeighborsClassifier

#從k=1開始測試
clf=KNeighborsClassifier(n_neighbors=29,p=2,weights='distance',algorithm='brute')
clf.fit(X_train,y_train)
pred = clf.predict(X_test)

In [32]:
#測試KNN演算法的好壞
from sklearn.metrics import classification_report,confusion_matrix
#將實際類別分為真正例（True Positive）、真負例（True Negative）、偽正例（False Positive）和偽負例（False Negative）
print(confusion_matrix(y_test,pred))

[[418  43]
 [150 169]]


In [33]:
#模型的精確度、召回率、F1分數和支持數等指標，用來評估模型對於每個類別的預測性能。
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

          -1       0.74      0.91      0.81       461
           1       0.80      0.53      0.64       319

    accuracy                           0.75       780
   macro avg       0.77      0.72      0.72       780
weighted avg       0.76      0.75      0.74       780



In [34]:
#pred 是模型在測試集上的預測結果
pred

array([-1,  1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1,
        1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1,
       -1, -1, -1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1,  1,  1,
       -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1

In [35]:
#返回模型在測試集上的預測準確度。它是模型正確預測的樣本數除以總樣本數的比例。
clf.score(X_test,y_test)

0.7525641025641026

In [36]:
#可以用來檢視模型是否存在過擬合的情況。
clf.score(X_train,y_train)

1.0

In [40]:
# 使用 kneighbors 方法取得最近鄰居的索引和距離
# 這裡假設你想查看測試集中第一個樣本的最近鄰居(問)
test_sample_index = 0
n_neighbors = 5  # 可以自行指定想要查看的最近鄰居的數量

distances, indices = clf.kneighbors(X_test.iloc[[test_sample_index]], n_neighbors=n_neighbors)

# 打印最近鄰居的索引和距離
print(f"最近鄰居的索引: {indices}")
print(f"最近鄰居的距離: {distances}")

最近鄰居的索引: [[  66 1678  332 1686  214]]
最近鄰居的距離: [[1.67718512 2.57670916 2.87269804 2.98435084 3.04195215]]


In [42]:
# 使用 kneighbors 方法取得最近鄰居的索引和距離
# n_neighbors 設定為 5 代表找最近的 5 個鄰居
distances, indices = clf.kneighbors(X_test, n_neighbors=5)

# 合併所有測試樣本的最近鄰居索引
all_indices = np.concatenate(indices)
all_distances = np.concatenate(distances)

# 將索引和距離組合成一個 2D 陣列，方便排序
combined_data = np.column_stack((all_indices, all_distances))

# 按照距離重新排序
sorted_combined_data = combined_data[np.argsort(combined_data[:, 1])]

# 取最近鄰居的前5筆
top5_neighbors_combined_indices = sorted_combined_data[:5, 0].astype(int)
top5_neighbors_combined_distances = sorted_combined_data[:5, 1]
# 根據最近鄰居的索引抓取預測值
#top5_neighbors_predictions = pred[top5_neighbors_combined_indices[top5_neighbors_combined_indices < len(pred)]]


# 打印最近鄰居的前5筆索引和距離
print("最近鄰居的前5筆索引:")
print(top5_neighbors_combined_indices)
print("最近鄰居的前5筆距離:")
print(top5_neighbors_combined_distances)
#print("最近鄰居的前5筆預測值:")
#print(top5_neighbors_predictions)

最近鄰居的前5筆索引:
[1013   69 1762   32 1516]
最近鄰居的前5筆距離:
[0.14429926 0.15923667 0.17528081 0.1855746  0.19013852]


In [39]:
# 假設最近鄰居的索引是 indices[0]
nearest_neighbors_indices = top5_neighbors_combined_indices

# 從原始資料 df 中抓取相應的數值
nearest_neighbors_data = df.iloc[nearest_neighbors_indices]

# 打印最近鄰居的資料
print(nearest_neighbors_data)

      證券代碼           簡稱      年月  市值(百萬元)  收盤價(元)_年      本益比    股價淨值比    股價營收比  \
1013  2409  友達           200212    81662     11.98   7.2606  0.61816  0.63554   
69    1907   永豐餘         199712    19049      8.50  29.3103  0.64492  0.53292   
1762  6209   今國光         200512     9392     64.04   9.8827  2.05780  2.19320   
32    1314   中石化         199712    36484     23.21  14.9742  1.28020  2.14110   
1516  2029  盛餘           200412    13842     28.41   4.7909  1.15300  0.47508   

      M淨值報酬率─稅後  資產報酬率ROA  ...   利潤邊際NPM   負債/淨值比   M流動比率   M速動比率  M存貨週轉率 (次)  \
1013   0.046625  0.077384  ...  0.079571  0.65970  197.70  155.73        7.25   
69     0.010812  0.022234  ...  0.018374  1.05630  133.00   88.87        5.20   
1762   0.114390  0.198280  ...  0.220370  0.73335  304.05  227.28        3.25   
32     0.042116  0.085291  ...  0.142670  1.02510   83.66   44.49        7.77   
1516   0.189020  0.240340  ...  0.099200  0.27152  289.88  130.31        8.50   

      M應收帳款週轉次  M營業利益成長率  